"""
BMAD GUI - File Operations
文件操作相关函数
"""

import json
import shutil
import logging
from datetime import datetime
from pathlib import Path

import yaml

from config import (
    RECENT_PROJECTS_FILE, MAX_RECENT_PROJECTS,
    DATA_DIR, BMAD_TEMPLATE_DIR, CLAUDE_TEMPLATE_DIR
)

logger = logging.getLogger("bmad-gui")


def is_bmad_project(path: Path) -> bool:
    """检查目录是否为 BMAD 项目"""
    bmad_dir = path / ".bmad"
    config_file = bmad_dir / "bmm" / "config.yaml"
    return bmad_dir.exists() and config_file.exists()


def parse_bmad_config(path: Path) -> dict | None:
    """解析 BMAD 配置文件，失败返回 None"""
    config_file = path / ".bmad" / "bmm" / "config.yaml"
    try:
        with open(config_file, 'r', encoding='utf-8') as f:
            config = yaml.safe_load(f)
        return {
            'user_name': config.get('user_name', 'Unknown'),
            'communication_language': config.get('communication_language', 'english'),
            'output_folder': config.get('output_folder', 'md/'),
            'project_name': config.get('project_name', path.name),
        }
    except Exception as e:
        logger.error(f"配置解析失败: {e}")
        return None


async def load_recent_projects() -> list:
    """加载最近项目列表"""
    if not RECENT_PROJECTS_FILE.exists():
        return []
    try:
        with open(RECENT_PROJECTS_FILE, 'r', encoding='utf-8') as f:
            data = json.load(f)
        if isinstance(data, list):
            return data
        elif isinstance(data, dict) and 'projects' in data:
            return data['projects']
        return []
    except Exception as e:
        logger.error(f"加载最近项目失败: {e}")
        return []


async def save_recent_projects(projects: list) -> None:
    """保存最近项目列表"""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    try:
        with open(RECENT_PROJECTS_FILE, 'w', encoding='utf-8') as f:
            json.dump(projects, f, ensure_ascii=False, indent=2)
    except Exception as e:
        logger.error(f"保存最近项目失败: {e}")


async def update_recent_projects(path: str, name: str) -> None:
    """更新最近项目列表（添加或移动到顶部）"""
    projects = await load_recent_projects()
    projects = [p for p in projects if p.get('path') != path]
    projects.insert(0, {
        'path': path,
        'name': name,
        'lastOpened': datetime.now().isoformat()
    })
    projects = projects[:MAX_RECENT_PROJECTS]
    await save_recent_projects(projects)


def create_bmad_structure(path: Path, modules: list) -> None:
    """创建 .bmad 目录结构，从模板目录复制完整 BMAD 文件"""
    bmad_dir = path / ".bmad"
    bmad_dir.mkdir(exist_ok=True)

    if not BMAD_TEMPLATE_DIR.exists():
        logger.warning(f"BMAD 模板目录不存在: {BMAD_TEMPLATE_DIR}，将创建空目录结构")
        if 'bmm' in modules:
            bmm_dir = bmad_dir / "bmm"
            bmm_dir.mkdir(exist_ok=True)
            (bmm_dir / "agents").mkdir(exist_ok=True)
            (bmm_dir / "workflows").mkdir(exist_ok=True)
        if 'core' in modules:
            core_dir = bmad_dir / "core"
            core_dir.mkdir(exist_ok=True)
        return

    if 'bmm' in modules:
        src_bmm = BMAD_TEMPLATE_DIR / "bmm"
        dst_bmm = bmad_dir / "bmm"
        if src_bmm.exists():
            shutil.copytree(src_bmm, dst_bmm, dirs_exist_ok=True)
            logger.info(f"已复制 bmm 模块: {src_bmm} -> {dst_bmm}")
        else:
            dst_bmm.mkdir(exist_ok=True)
            (dst_bmm / "agents").mkdir(exist_ok=True)
            (dst_bmm / "workflows").mkdir(exist_ok=True)

    if 'core' in modules:
        src_core = BMAD_TEMPLATE_DIR / "core"
        dst_core = bmad_dir / "core"
        if src_core.exists():
            shutil.copytree(src_core, dst_core, dirs_exist_ok=True)
            logger.info(f"已复制 core 模块: {src_core} -> {dst_core}")
        else:
            dst_core.mkdir(exist_ok=True)

    for extra_dir in ['_cfg', 'docs']:
        src_extra = BMAD_TEMPLATE_DIR / extra_dir
        dst_extra = bmad_dir / extra_dir
        if src_extra.exists():
            shutil.copytree(src_extra, dst_extra, dirs_exist_ok=True)
            logger.info(f"已复制 {extra_dir} 目录: {src_extra} -> {dst_extra}")


def create_claude_structure(path: Path) -> None:
    """创建 .claude 目录结构"""
    claude_dir = path / ".claude"

    if not CLAUDE_TEMPLATE_DIR.exists():
        logger.warning(f"Claude 模板目录不存在: {CLAUDE_TEMPLATE_DIR}，将创建空目录结构")
        claude_dir.mkdir(exist_ok=True)
        (claude_dir / "commands").mkdir(exist_ok=True)
        return

    shutil.copytree(CLAUDE_TEMPLATE_DIR, claude_dir, dirs_exist_ok=True)
    logger.info(f"已复制 .claude 目录: {CLAUDE_TEMPLATE_DIR} -> {claude_dir}")


def generate_config_yaml(path: Path, config: dict) -> str:
    """生成 config.yaml 内容"""
    project_name = path.name
    date_str = datetime.now().strftime("%Y-%m-%d")

    content = f"""# BMM Module Configuration
# Generated by BMAD GUI
# Date: {date_str}

project_name: {project_name}
user_name: {config.get('user_name', 'Unknown')}
communication_language: {config.get('communication_language', 'chinese')}
output_folder: {config.get('output_folder', 'md/')}

# Core Configuration Values
bmad_folder: .bmad
"""
    return content


def find_workflow_status_file(project_path: Path) -> Path | None:
    """查找工作流状态文件"""
    for search_path in [
        project_path / "md" / "bmm-workflow-status.yaml",
        project_path / "bmm-workflow-status.yaml",
    ]:
        if search_path.exists():
            return search_path
    return None


def find_sprint_status_file(project_path: Path) -> Path | None:
    """查找 Sprint 状态文件"""
    for search_path in [
        project_path / "md" / "sprint-artifacts" / "sprint-status.yaml",
        project_path / "md" / "sprint-status.yaml",
        project_path / "sprint-status.yaml",
    ]:
        if search_path.exists():
            return search_path
    return None
